'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site1
    
    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''Inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Inicio As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnClientes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClientes As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''AgregarC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AgregarC As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''ModificarC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModificarC As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''GestionarC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GestionarC As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''ParameComisionesC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ParameComisionesC As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''VisualizacionCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VisualizacionCC As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnComisiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnComisiones As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''comisionesV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comisionesV As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''comisionesCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comisionesCC As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''BtnEjecutiva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEjecutiva As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''EjeCrearEje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EjeCrearEje As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''EjeParameComiVentas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EjeParameComiVentas As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''BtnPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPago As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''FBuscarFactura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FBuscarFactura As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''FPagos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FPagos As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''FTipopago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FTipopago As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''FTipoPOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FTipoPOS As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnMantenimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMantenimiento As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''MObjetos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MObjetos As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''MParametros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MParametros As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''MPreguntas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPreguntas As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''MRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MRoles As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''MRegistrarU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MRegistrarU As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''MGestionU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MGestionU As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''MRPermisos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MRPermisos As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''BtnSoporteIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSoporteIT As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''ITGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ITGestion As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''ITEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ITEstado As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''ITPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ITPrincipal As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''ITHistorial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ITHistorial As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''Reportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reportes As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''CrearSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CrearSolicitud As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnPerfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPerfil As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''PCambioContraseña control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PCambioContraseña As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''PConfigPregunta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PConfigPregunta As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''CerraSesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CerraSesion As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ContentPlaceHolder1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''A3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A3 As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
