'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Pagos
    
    '''<summary>
    '''txtfactura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfactura As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClient As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtSubtotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubtotal As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtisv15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtisv15 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtSerie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerie As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtRSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRSocial As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtdescuento15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdescuento15 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtisv18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtisv18 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtfolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfolio As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtrtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtrtn As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtdescuento18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdescuento18 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotal As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''cbfpago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbfpago As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtisv15BD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtisv15BD As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtdescuento8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdescuento8 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''cbpos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbpos As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtisv18BD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtisv18BD As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtTotalBD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalBD As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtSubtotalBd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubtotalBd As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtRetenciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRetenciones As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''BtnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGuardar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''BtnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancelar As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
