'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BuscarCXC
    
    '''<summary>
    '''TXtBuscar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXtBuscar1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblTotalesCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalesCliente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Gvbuscarcliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Gvbuscarcliente As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''LblPaginadorCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPaginadorCliente As Global.System.Web.UI.WebControls.Label
End Class
