'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EjecutivaCC
    
    '''<summary>
    '''TxtFechaInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFechaInicio As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''TxtFechaFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFechaFinal As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''txtcobrosnetos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcobrosnetos As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtcanjes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcanjes As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtretenciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtretenciones As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtbac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbac As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''Txtficohsa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtficohsa As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''Txtcomisionable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtcomisionable As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtcomision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcomision As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtcomisioncredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcomisioncredito As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtcomisionfacturas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcomisionfacturas As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''btnagregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnagregar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblTotalesComisiones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalesComisiones As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GvComisionesCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GvComisionesCC As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''LblPaginadorComisionesCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPaginadorComisionesCC As Global.System.Web.UI.WebControls.Label
End Class
