'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GestionCC
    
    '''<summary>
    '''BtnBuscarCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBuscarCliente As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''TxtNombreCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombreCuenta As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtACliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtACliente As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtsaldo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsaldo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txttipocliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttipocliente As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtdcredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdcredito As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtlcredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlcredito As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtejecutiva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtejecutiva As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtemail As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txttelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttelefono As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lblGestionartotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGestionartotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GVGestionar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVGestionar As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblPaginadorGestionar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaginadorGestionar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnGestionar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGestionar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblGestionadostotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGestionadostotal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GVGestionados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVGestionados As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''LblPaginadorGestionados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPaginadorGestionados As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblTotalpagados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTotalpagados As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GVPAgados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPAgados As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''LblPaginadorpagos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPaginadorpagos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtClientemodal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientemodal As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''cbtipodGestionmodal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbtipodGestionmodal As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''txtfechaprogramadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfechaprogramadas As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl
    
    '''<summary>
    '''txtdesripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdesripcion As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''btnguardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnguardar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''Txtserie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtserie As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtRazonSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRazonSocial As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtCodCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCodCliente As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtSubTotalges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSubTotalges As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtDescquince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDescquince As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''Txtfactura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtfactura As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtRtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRtn As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''Txtfechages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtfechages As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtISV15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtISV15 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''Txtdesdieciocho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtdesdieciocho As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TXTFolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTFolio As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtClienteges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtClienteges As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtFpago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFpago As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtISV18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtISV18 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''TxtTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTotal As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtseriemo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtseriemo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtfechapagomo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfechapagomo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtfacturamo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfacturamo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtfechaprogramacionmo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfechaprogramacionmo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtfoliomo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfoliomo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txttpagomo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttpagomo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtidclienteGes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidclienteGes As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtfechaemisionges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfechaemisionges As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtusuarioges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtusuarioges As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtfechaprogramacionges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfechaprogramacionges As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txttipogestionges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttipogestionges As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtdescripcionges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdescripcionges As Global.System.Web.UI.HtmlControls.HtmlTextArea
End Class
