'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VisualizaciondeGestiones
    
    '''<summary>
    '''lbltotlapromesas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltotlapromesas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GVPromesas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVPromesas As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblPaginadorCXCPromesas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaginadorCXCPromesas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLlamadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLlamadas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GVLlamadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVLlamadas As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''LblPaginadorLlamadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPaginadorLlamadas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblVisitas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblVisitas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GVVisitas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVVisitas As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''LblPaginadorVisitas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPaginadorVisitas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtidclienteGes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidclienteGes As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtfechaemisionges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfechaemisionges As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtusuarioges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtusuarioges As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtfechaprogramacionges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfechaprogramacionges As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txttipogestionges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttipogestionges As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtdescripcionges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdescripcionges As Global.System.Web.UI.HtmlControls.HtmlTextArea
End Class
